### ISSUE TITLE
Crash when showing twitter web dialog on login

### ISSUE THREAD

**Issue by maxbryan** [ParsePlatform/ParseTwitterUtils-iOS#1]
Thanks for your help!
<img width="1749" alt="screen shot 2015-10-08 at 7 56 18 pm" src="https://cloud.githubusercontent.com/assets/3952680/10383597/c49e182a-6df6-11e5-9028-94f698b65e1c.png">

**Comment by nlutsenko** [comment]
Hey @maxbryan, we've seen couple of reports about these so far...
The general issue behind these - wrong redirect url specified in Twitter settings or invalid tokens provided.

Any chance you can post a code snippet or a better a repro project here that would reproduce the issue?

**Comment by maxbryan** [comment]
Looks like I had the wrong key in my application settings on parse. Thanks

**Comment by nlutsenko** [comment]
Glad it worked! Let me know if there is anything else I can help you with.
