### ISSUE TITLE
Exception with PFTwitterUtils.logInInBackground()

### ISSUE THREAD

**Issue by weiwarren** [ParsePlatform/ParseTwitterUtils-iOS#11]
@nlutsenko  I created a simple view controller in xcode 6 with swift 1.2 to test ParseTwitterUtils-IOS 1.9.1 using the following code 
```swift
import UIKit

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
    }

    @IBAction func twitterClicked(sender: AnyObject) {
        PFTwitterUtils.logInInBackground()
    }
}

```

1. After a twitter login popped up, click the <b>Cancel</b> button
2. Tap <b>Return to [Twitter App name]</b> and app crashes

<b>Exception log:</b>

<pre>
  *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: Invalid request token.)'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010a982c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010b4d8bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010a887af8 -[__NSDictionaryM setObject:forKey:] + 968
	3   testparse                           0x0000000107f54b4e +[NSURL(OAuthAdditions) PF_ab_parseURLQueryString:] + 541
	4   testparse                           0x0000000107f4de6b __65-[PF_Twitter _getAccessTokenForWebAuthAsync:requestSecret:token:]_block_invoke + 127
	5   CFNetwork                           0x0000000109a08beb __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 157
	6   Foundation                          0x000000010b11057f __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	7   Foundation                          0x000000010b0510b2 -[NSBlockOperation main] + 98
	8   Foundation                          0x000000010b033774 -[__NSOperationInternal _start:] + 645
	9   Foundation                          0x000000010b033383 __NSOQSchedule_f + 184
	10  libdispatch.dylib                   0x000000010c169614 _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x000000010c1506a7 _dispatch_queue_drain + 2176
	12  libdispatch.dylib                   0x000000010c14fcc0 _dispatch_queue_invoke + 235
	13  libdispatch.dylib                   0x000000010c1533b9 _dispatch_root_queue_drain + 1359
	14  libdispatch.dylib                   0x000000010c154b17 _dispatch_worker_thread3 + 111
	15  libsystem_pthread.dylib             0x000000010c4eea9d _pthread_wqthread + 729
	16  libsystem_pthread.dylib             0x000000010c4ec3dd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
</pre>

**Comment by aphex3k** [comment]
I have the same issue using it as a framework in swift

**Comment by mitchellporter** [comment]
@weiwarren Why did you close this without an update?

**Comment by aphex3k** [comment]
@mitchellporter The solution can be found by looking at the issue #348.
