### ISSUE TITLE
NSURLConnection sendAsynchronousRequest is now Deprecated

### ISSUE THREAD

**Issue by duffek** [ParsePlatform/ParseTwitterUtils-iOS#22]
NSURLConnection sendAsynchronousRequest is now deprecated. We need a way to make the call to using NSURLSession and still sign it with the twitter auth.

**Comment by nlutsenko** [comment]
Hey @duffek, are you sure you are referencing the right repo?
There is no usages of NSURLConnection in this repo or our main SDK.
[Here](https://github.com/ParsePlatform/ParseTwitterUtils-iOS/search?utf8=%E2%9C%93&q=NSURLConnection) is the search query.

**Comment by duffek** [comment]
Currently we use:
    NSURL *verify = [NSURL URLWithString:urlString];
    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:verify];
    [[PFTwitterUtils twitter] signRequest:request];            
    NSOperationQueue * queue = [[NSOperationQueue alloc] init];
    [NSURLConnection sendAsynchronousRequest:request queue:queue     completionHandler:^(NSURLResponse *response, NSData *data, NSError *connectionError) {
        if ( connectionError == nil)
        {
        }
    }];

Now that Apple deprecated `sendAsynchronousRequest:request` we need a way to make this request with an NSURLSession. Currently `[[PFTwitterUtils twitter] signRequest:request];` is used to add the authentication to the call. the `NSMutableURLRequest` will be no longer used in the future so this needs to change.

**Comment by nlutsenko** [comment]
I was able to find the code in our docs that needs to be updated (should be fixed with https://github.com/ParsePlatform/Docs/pull/316).
Take a look at the code snippet in the pull request - it has a NSURLSession example that you could use.

Was it the part you were referencing or there is something else I might have missed?

**Comment by duffek** [comment]
Yes that is it. Thank you for your quick response. If only Parse as a whole would be so vigilant about their documentation as a whole... 

Thanks again and I'll search harder through the repo before starting an issue.
