### ISSUE TITLE
twitter login isn't working and hasn't been working for over 24 hours

### ISSUE THREAD

**Issue by hashtagru** [ParsePlatform/ParseTwitterUtils-iOS#24]
users trying to login go no where - rending the app useless 

i'm locked out of my own app

**Comment by hashtagru** [comment]
PFTwitterUtils  The Parse/Twitter login tool is what isn't working - i get mixed messages from parse - they recognized it and another person sent me here

**Comment by acegreen** [comment]
+1

**Comment by billylo1** [comment]
I encountered the same issue...  when PFRESTUserCommand tries to login, it failed with a [Error]: The request timed out. (Code: 100, Version: 1.12.0).   I haven't been able to track down where the error is originated from.  The code that reported this error is inside Parse Core (1.12).  I am going to try reverting to an older version of Parse.

**Comment by hashtagru** [comment]
Parse says they are working on it - but no updates for over 14 hours

**Comment by hashtagru** [comment]
https://developers.facebook.com/bugs/914545211986956/ in case you want to follow that bug

**Comment by acegreen** [comment]
**Problem fixed**

**Comment by nlutsenko** [comment]
Hey guys, just wanted to let everyone here now that the issue is ultimately fixed and we rolled out a patch since about 7 hours ago. Please comment/reopen this issue if you still experience this problem.
