### ISSUE TITLE
PFTwitterUtils should be initialized after setting up Parse. - Still crashes

### ISSUE THREAD

**Issue by adrianbrink** [ParsePlatform/ParseTwitterUtils-iOS#30]
Hi,

This is my didFinishLaunchingWithOptions method.

`    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        
        // Set initial VC in code
        // https://stackoverflow.com/questions/24046898/how-do-i-create-a-new-swift-project-without-using-storyboards#24047050
        window = UIWindow(frame: UIScreen.mainScreen().bounds)
        if let window = window {
            window.rootViewController = LoginVC()
            window.makeKeyAndVisible()
        }
		
        // Configure Parse
        let config = ParseClientConfiguration {
            $0.applicationId = "xxx"
            $0.server = "xxx"
        }
        Parse.initializeWithConfiguration(config)
        
        // Facebook Login
        PFFacebookUtils.initializeFacebookWithApplicationLaunchOptions(launchOptions)
		
	// Twitter Login
	PFTwitterUtils.initializeWithConsumerKey("xxx", consumerSecret: "xxx")
		
        return true
    }`

The error is.

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'PFTwitterUtils should be initialized after setting up Parse.'

Am I miss-understanding what is meant by initializing after setting up Parse, because as far as I can tell I am doing the twitter stuff afterwards.

This happens on the simulator and an iPhone6S.

Any help is appreciated.

**Comment by crayment** [comment]
The SDK is incorrectly checking that parse was setup with an `applicationId` AND a `clientKey`. The `clientKey` is no longer a required value when initializing parse. You can get farther by specifying a `clientKey` anyway.

Unfortunately I seem to run into issues later when linking accounts I get an exception:

> 'No registered authentication delegate found for `twitter` authentication type.

**Comment by nlutsenko** [comment]
Already fixed on master, and is shipping in the next version early next week.
Sorry for the delay, guys...
