### ISSUE TITLE
Twitter link with new parse sever

### ISSUE THREAD

**Issue by anoopnimkar** [ParsePlatform/ParseTwitterUtils-iOS#35]
We are trying to test twitter link and facebook link after migrating to Parse server and hitting issues with Twitter link. We see following error on console log,
**Twitter auth is invalid for this user. (Code: 101, Version: 1.13.0)**

We have all config set on index.js with Twitter secret and client key and using latest SDKs

Facebook link works fine.

Any suggestions on how to debug the issue?

**Comment by nlutsenko** [comment]
cc @flovilmart

**Comment by flovilmart** [comment]
Can you run parse-server with VERBOSE=1 and send me the logs?

**Comment by flovilmart** [comment]
I just tested the module itself with a valid auth token and it all seem to work correctly.

In your index.js, can you confirm the options for twitter are in that form:
```
{
  consumer_key: 'MY_CONSUMER_KEY',
  consumer_secret: 'MY_CONSUMER_SECRET'
}
```

**Comment by anoopnimkar** [comment]
Thanks for your response. I had a typo in my consumer secret. It worked after fixing that. Thanks again!

**Comment by VinodJagtap** [comment]
@anoopnimkar  I am facing same problem as you , what you have exactly written in index.js file? I am new to this stuff its not working. Thank you.
